### ISSUE TITLE
[feat] Emoji support for freewords

### ISSUE THREAD

**Issue by billchenchina** [ZTGeng/ZTGeng.github.io#1]
[Freewords](https://github.com/ZTGeng/ZTGeng.github.io/blob/master/tool/js/freewords.js) now doesn't support Emoji.

![image](https://user-images.githubusercontent.com/7758042/76601483-fa9c8f80-6543-11ea-85a4-bdb787c08218.png)

Here are some resources that may be useful:

[orling/grapheme-splitter](https://github.com/orling/grapheme-splitter)

[MDN codePointAt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/codePointAt)

**Comment by ZTGeng** [comment]
Thanks for the note. Fixed with latest update.
